version: "3.7"
services:
  database:
    image: mysql:5.7
    ports:
      - "33060:3306"
    environment:
        - MYSQL_ROOT_PASSWORD=test

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - database:db
    ports:
      - "8090:80"
